//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_nos
    {
        public int id { get; set; }
        public string bill_type { get; set; }
        public string financial_code { get; set; }
        public int bill_no { get; set; }
    }
}
