//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ledger_register
    {
        public int id { get; set; }
        public string ledger_code { get; set; }
        public string ledger { get; set; }
        public string alternate_name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public Nullable<bool> is_editable { get; set; }
        public Nullable<bool> is_removable { get; set; }
        public Nullable<bool> is_enabled { get; set; }
        public string type { get; set; }
        public string group_code { get; set; }
        public string special_code { get; set; }
        public string unique_id { get; set; }
        public string a_group_code { get; set; }
        public string b_group_code { get; set; }
        public string c_group_code { get; set; }
        public string details1 { get; set; }
        public string details2 { get; set; }
        public string details3 { get; set; }
        public string details4 { get; set; }
        public string details5 { get; set; }
        public string details6 { get; set; }
    }
}
