//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_register
    {
        public int id { get; set; }
        public string product_code { get; set; }
        public string product { get; set; }
        public string alternate_name { get; set; }
        public Nullable<bool> is_enabled { get; set; }
        public string type { get; set; }
        public string group_code { get; set; }
        public string stockin_unit_code { get; set; }
        public string stockout_unit_code { get; set; }
    }
}
