//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class unit_register
    {
        public int id { get; set; }
        public string unit_code { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> unit_value { get; set; }
        public string type { get; set; }
        public string group_code { get; set; }
    }
}
